---
- name: Update web servers
  hosts: web
  become: true
  gather_facts: false
  # remote_user: ec2-user
  tasks:
  - name: Install apache
    #ansible.builtin.yum:
    yum:
      name: httpd
      state: latest
    notify:
    - Start the server
  # - name: Start the server
  #   service:
  #     name: httpd
  #     state: started
  - name: copy file to server
    # copy: src=/home/ansible/index.html dest=/var/www/html
    copy:
      src: index.html
      dest: /var/www/html
  handlers:
  - name: Start the server
    service:
      name: httpd
      state: started
